### ISSUE TITLE
Poller does not re-connect after sleep? 

### ISSUE THREAD

**Issue by dky** [IslandJohn/TeamRadar#5]
2016/03/04 07:40:36 main.pollTfsRoomMessages:305 dial tcp: lookup islandjohn.visualstudio.com: no such host
2016/03/04 07:40:36 main.pollTfsRoomUsers:223 dial tcp: lookup islandjohn.visualstudio.com: no such host
2016/03/04 07:40:36 main.pollTfsRoomMessages:305 dial tcp: lookup islandjohn.visualstudio.com: no such host
2016/03/04 07:40:36 main.pollTfsRoomUsers:223 dial tcp: lookup islandjohn.visualstudio.com: no such host
2016/03/04 07:41:41 main.pollTfsRooms:129 read tcp 192.168.1.119:52615->23.98.150.230:443: read: operation timed out

**Comment by IslandJohn** [comment]
No, each routine gives up after 3 errors. Higher level routines (polling of users and messages) will be restarted by the room polling routine, but if the main routine errors out 3 times, the entire thing will give up. It's expected that the UI would handle this and restart the poller as needed. We can re-evaluate this if the Go poller becomes more user-centric. As it is, it's a very dumb low-level component.

**Comment by dky** [comment]
Steps to reproduce: Connect through terminal with go app. Close lid, resume. Times out. Perhaps some type of reconnect retry loop?

**Comment by dky** [comment]
I see, Thanks
